# Generated by inputting Fisher test into ChatGPT 5.3 and asking for it to be converted to permutation testing,
# as I did not 
###############################################################
# PERMUTATION TEST FOR CROSS-DISORDER DEG OVERLAP
#
# Background universe:
# all annotated human genes in Ensembl
# (~60k–80k genes including protein-coding, lncRNA, pseudogenes)
#
# Purpose:
# test whether overlap between DEG lists exceeds random expectation
#
# Method:
# empirical permutation test
#
###############################################################

library(dplyr)
library(biomaRt)
library(ggplot2)
library(tidyr)

set.seed(1)

###############################################################
# 1. OBTAIN FULL HUMAN GENE UNIVERSE
###############################################################

mart <- useMart(
    "ensembl",
    dataset = "hsapiens_gene_ensembl"
)

# retrieve all annotated genes
gene_universe_df <- getBM(
    attributes = c(
        "ensembl_gene_id",
        "gene_biotype"
    ),
    mart = mart
)

# vector of all Ensembl gene IDs
gene_universe <- unique(
    gene_universe_df$ensembl_gene_id
)

length(gene_universe)

# expected:
# ~60k–80k genes


###############################################################
# 2. CREATE DEG LISTS PER DISORDER
###############################################################

deg_lists_df <- meta_disorder %>%
    group_by(DISORDER) %>%
    summarise(
        genes = list(unique(GENEID)),
        n_deg = n_distinct(GENEID),
        .groups = "drop"
    )

deg_lists <- setNames(
    deg_lists_df$genes,
    deg_lists_df$DISORDER
)

deg_lists_df


###############################################################
# 3. PERMUTATION TEST FUNCTION
###############################################################

permute_overlap <- function(
        genes_A,
        genes_B,
        universe,
        n_perm = 10000
){
    
    # number of DEGs per disorder
    k_A <- length(genes_A)
    k_B <- length(genes_B)
    
    # observed overlap
    observed_overlap <- length(
        intersect(genes_A, genes_B)
    )
    
    # simulate random overlaps
    simulated_overlaps <- replicate(n_perm, {
        
        random_A <- sample(universe, k_A)
        
        random_B <- sample(universe, k_B)
        
        length(intersect(random_A, random_B))
        
    })
    
    data.frame(
        
        observed_overlap = observed_overlap,
        
        expected_overlap =
            mean(simulated_overlaps),
        
        sd_expected =
            sd(simulated_overlaps),
        
        z_score =
            (observed_overlap -
                 mean(simulated_overlaps)) /
            sd(simulated_overlaps),
        
        empirical_p =
            mean(simulated_overlaps >=
                     observed_overlap)
        
    )
    
}


###############################################################
# 4. RUN PERMUTATION TEST FOR ALL DISORDER PAIRS
###############################################################

disorders <- names(deg_lists)

pair_list <- combn(
    disorders,
    2,
    simplify = FALSE
)

perm_results <- lapply(pair_list, function(pair){
    
    d1 <- pair[1]
    d2 <- pair[2]
    
    res <- permute_overlap(
        
        genes_A =
            deg_lists[[d1]],
        
        genes_B =
            deg_lists[[d2]],
        
        universe =
            gene_universe,
        
        n_perm = 5000
        
    )
    
    data.frame(
        
        disorder1 = d1,
        
        disorder2 = d2,
        
        n_deg_d1 =
            length(deg_lists[[d1]]),
        
        n_deg_d2 =
            length(deg_lists[[d2]]),
        
        res
        
    )
    
})

perm_df <- do.call(
    rbind,
    perm_results
)


###############################################################
# 5. MULTIPLE TESTING CORRECTION
###############################################################

perm_df$p_adj_fdr <- p.adjust(
    
    perm_df$empirical_p,
    
    method = "fdr"
    
)


###############################################################
# 6. SAVE RESULTS TABLE
###############################################################

write.csv(
    
    perm_df,
    
    "results/tables/permutation_overlap_all_annotated_genes.csv",
    
    row.names = FALSE
    
)


###############################################################
# 7. COMPUTE EXCESS OVERLAP
###############################################################

perm_df$excess_overlap <-
    
    perm_df$observed_overlap -
    
    perm_df$expected_overlap


###############################################################
# 8. VISUALIZATION
###############################################################

# heatmap of excess overlap

p_excess <- ggplot(
    
    perm_df,
    
    aes(
        
        x = disorder1,
        
        y = disorder2,
        
        fill = excess_overlap
        
    )
    
) +
    
    geom_tile(
        
        color = "white"
        
    ) +
    
    scale_fill_gradient2(
        
        low = "blue",
        
        mid = "white",
        
        high = "red"
        
    ) +
    
    theme_minimal()

ggsave(
    
    "results/figures/permutation_excess_overlap_all_genes.png",
    
    p_excess,
    
    width = 6,
    
    height = 5,
    
    dpi = 300
    
)



###############################################################
# heatmap of statistical significance
###############################################################

p_sig <- ggplot(
    
    perm_df,
    
    aes(
        
        x = disorder1,
        
        y = disorder2,
        
        fill = -log10(p_adj_fdr)
        
    )
    
) +
    
    geom_tile(
        
        color = "white"
        
    ) +
    
    scale_fill_gradient(
        
        low = "white",
        
        high = "red"
        
    ) +
    
    theme_minimal()

ggsave(
    
    "results/figures/permutation_significance_all_genes.png",
    
    p_sig,
    
    width = 6,
    
    height = 5,
    
    dpi = 300
    
)



###############################################################
# 9. SAVE MATRIX FORMAT
###############################################################

overlap_matrix <- perm_df %>%
    
    select(
        
        disorder1,
        
        disorder2,
        
        excess_overlap
        
    ) %>%
    
    pivot_wider(
        
        names_from = disorder2,
        
        values_from = excess_overlap
        
    )

write.csv(
    
    overlap_matrix,
    
    "results/tables/permutation_overlap_matrix_all_genes.csv",
    
    row.names = FALSE
    
)


###############################################################
# OUTPUT FILES
###############################################################

# tables

# permutation_overlap_all_annotated_genes.csv
# permutation_overlap_matrix_all_genes.csv

# figures

# permutation_excess_overlap_all_genes.png
# permutation_significance_all_genes.png


###############################################################
# INTERPRETATION
###############################################################

# observed_overlap
# number of shared DEGs between disorders

# expected_overlap
# overlap expected by chance

# excess_overlap
# additional overlap beyond random expectation

# empirical_p
# probability of observing equal or greater overlap

# p_adj_fdr
# FDR-corrected significance


###############################################################
# NOTES
###############################################################

# uses all annotated genes:
# protein-coding
# lncRNA
# pseudogenes
# antisense transcripts
# readthrough transcripts

# appropriate for RNA-seq studies where noncoding RNAs are included

###############################################################